# Generated by Django 3.1 on 2022-01-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200831_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='location',
            field=models.CharField(choices=[('HO', 'Home'), ('PO', 'Portfolio')], default='HO', max_length=60),
        ),
        migrations.AddField(
            model_name='images',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
