# Generated by Django 3.1 on 2022-02-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20220225_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.CharField(choices=[('HO', 'Home'), ('PO', 'Portfolio'), ('POR', 'Portraits'), ('BO', 'Boudoir'), ('WE', 'Wedding'), ('CO', 'Couples'), ('EL', 'Elopement'), ('EN', 'Engagement')], default='HO', max_length=60),
        ),
    ]
