# Generated by Django 3.1 on 2022-03-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20220226_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.CharField(choices=[('BG', 'Background'), ('HO', 'Home'), ('PO', 'Portfolio'), ('POR', 'Portraits'), ('BO', 'Boudoir'), ('WE', 'Wedding'), ('CO', 'Couples'), ('EL', 'Elopement'), ('EN', 'Engagement')], default='HO', max_length=60),
        ),
    ]
